name: testCI

on:
  push:
    branches: [ "develop", "test" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Gradle
        uses: gradle/gradle-build-action@v2

      - name: Verify Gradle dependencies
        run: gradle dependencies

      - name: Build with Gradle
        run: gradle build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run unit tests with Gradle
      run: ./gradlew test

    - name: Unit Test
      run: ./gradlew Test1

    - name: Android Test Report
      uses: asadmansr/android-test-report-action@v1.2.0
      if: ${{ always() }} # Ejecuta el reporte siempre
